<?php

namespace Tests\Feature\Api;

use Tests\TestCase;
use Illuminate\Support\Facades\DB;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use App\Modules\User\Models\User;
use App\Modules\Department\Models\Department;
use App\Modules\Attendance\Services\AttendanceGeoGate;

/**
 *  Feature tests for the Stefan Attendance API.
 *
 *  Coverage:
 *    - 401 when no JWT / API key is provided
 *    - 404 when geo / department / employee does not exist
 *    - 403 when caller's geo does not match
 *    - 422 when from/to are malformed or > 90 days
 *    - 200 happy path with shape assertions for each endpoint
 *
 *  Notes for the reviewer:
 *    - These tests use DatabaseTransactions so nothing persists. They do
 *      NOT use RefreshDatabase because the EVOX schema relies on stored
 *      procedures, triggers, and a typo'd `drt_summary_report` table that
 *      the migration set has no down() reverser for — re-creating the DB
 *      from migrations does not produce a usable test fixture.
 *    - To run locally:  php artisan test --filter=AttendanceTest
 *    - The test seeds minimal rows directly via the query builder so it
 *      does not depend on the BHR sync / SP layer being available.
 */
class AttendanceTest extends TestCase
{
    use DatabaseTransactions;

    /** @var int */ private $geoIdAllowed = 9001;
    /** @var int */ private $geoIdOther   = 9002;
    /** @var int */ private $callerId;
    /** @var int */ private $employeeAllowedId;
    /** @var int */ private $employeeOtherGeoId;
    /** @var int */ private $departmentId;
    /** @var string */ private $apiKey = 'test-api-key';

    protected function setUp(): void
    {
        parent::setUp();

        # Seed two geos in the country master (utc_timelog).
        DB::table('utc_timelog')->insert([
            [
                'country_id'        => $this->geoIdAllowed,
                'country_name'      => 'Testlandia',
                'country_time_zone' => 'UTC',
                'time_difference'   => '+00:00',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'country_id'        => $this->geoIdOther,
                'country_name'      => 'Otherland',
                'country_time_zone' => 'UTC',
                'time_difference'   => '+00:00',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);

        # Seed a department.
        $this->departmentId = (int) DB::table('departments')->insertGetId([
            'department_name' => 'Attendance API Test Dept ' . uniqid(),
            'description'     => 'auto-generated by AttendanceTest',
            'created_at'      => now(),
            'updated_at'      => now(),
        ]);

        # Seed three users:
        #   - caller in the allowed geo
        #   - employee in the allowed geo + dept
        #   - employee in the other geo
        $this->callerId          = $this->seedUser($this->geoIdAllowed, $this->departmentId);
        $this->employeeAllowedId = $this->seedUser($this->geoIdAllowed, $this->departmentId);
        $this->employeeOtherGeoId= $this->seedUser($this->geoIdOther,   $this->departmentId);

        # Seed one DTR + one summary row for the allowed employee on yesterday.
        $yesterday = date('Y-m-d', strtotime('-1 day'));
        DB::table('dtrs')->insert([
            'user_id'             => $this->employeeAllowedId,
            'date'                => $yesterday,
            'time_in'             => strtotime($yesterday . ' 09:00:00'),
            'time_out'            => strtotime($yesterday . ' 18:00:00'),
            'start_datetime'      => strtotime($yesterday . ' 09:00:00'),
            'end_datetime'        => strtotime($yesterday . ' 18:00:00'),
            'is_rest_day'         => 0,
            'source_type_tagging' => 'default',
            'created_at'          => now(),
            'updated_at'          => now(),
        ]);
        DB::table('drt_summary_report')->insert([
            'user_id'             => $this->employeeAllowedId,
            'supervisor_id'       => 0,
            'login_date'          => $yesterday,
            'reg_rendered_hours'  => 8.00,
            'reg_late'            => 0.00,
            'reg_undertime'       => 0.00,
            'created_at'          => now(),
            'updated_at'          => now(),
        ]);
    }

    /** @return int */
    private function seedUser(int $countryId, int $deptId): int
    {
        return (int) DB::table('users')->insertGetId([
            'first_name'    => 'Test',
            'last_name'     => 'User-' . uniqid(),
            'emp_num'       => 'EMP' . random_int(100000, 999999),
            'bhr_num'       => 'BHR' . random_int(100000, 999999),
            'email'         => 'test+' . uniqid() . '@example.test',
            'password'      => bcrypt('secret'),
            'department_id' => $deptId,
            'country_id'    => $countryId,
            'is_active'     => 1,
            'created_at'    => now(),
            'updated_at'    => now(),
        ]);
    }

    /** Helper — auth header pair (JWT + API key). */
    private function authHeaders(int $userId): array
    {
        $token = auth('api')->loginUsingId($userId);
        return [
            'Authorization' => 'Bearer ' . $token,
            'X-Api-Key'     => $this->apiKey,
            'Accept'        => 'application/json',
        ];
    }

    ###########################################################################
    ############################# Auth gate tests #############################
    ###########################################################################

    public function testRejectsRequestWithoutAuth()
    {
        $response = $this->getJson('/api/attendance/by-geo/' . $this->geoIdAllowed);
        $this->assertContains($response->status(), [401, 403], 'Unauthenticated requests must be rejected');
    }

    ###########################################################################
    ############################# 404 / not-found #############################
    ###########################################################################

    public function testReturns404ForUnknownGeo()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-geo/999999');

        $response->assertStatus(404)
            ->assertJsonStructure(['error' => ['message']]);
    }

    public function testReturns404ForUnknownDepartment()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-department/999999');

        $response->assertStatus(404);
    }

    public function testReturns404ForUnknownEmployee()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-employee/999999');

        $response->assertStatus(404);
    }

    ###########################################################################
    ############################# 403 / geo gating ############################
    ###########################################################################

    public function testReturns403WhenCallerCannotAccessGeo()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-geo/' . $this->geoIdOther);

        $response->assertStatus(403);
    }

    public function testReturns403WhenCallerRequestsForeignEmployee()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-employee/' . $this->employeeOtherGeoId);

        $response->assertStatus(403);
    }

    ###########################################################################
    ############################# 422 / validation ############################
    ###########################################################################

    public function testReturns422ForMalformedFromDate()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-geo/' . $this->geoIdAllowed . '?from=not-a-date');

        $response->assertStatus(422);
    }

    public function testReturns422WhenRangeExceeds90Days()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-geo/' . $this->geoIdAllowed
                . '?from=2025-01-01&to=2025-12-31');

        $response->assertStatus(422);
    }

    ###########################################################################
    ############################# 200 / happy path ############################
    ###########################################################################

    public function testByGeoHappyPath()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-geo/' . $this->geoIdAllowed);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'content' => [
                    'geo'        => ['id', 'country_name', 'time_zone'],
                    'date_range' => ['from', 'to'],
                    'pagination' => ['total', 'per_page', 'current_page', 'last_page'],
                    'employees',
                ],
            ]);
    }

    public function testByDepartmentHappyPath()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-department/' . $this->departmentId);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'content' => [
                    'department' => ['id', 'department_name'],
                    'date_range' => ['from', 'to'],
                    'pagination',
                    'employees',
                ],
            ]);
    }

    public function testByEmployeeHappyPath()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/attendance/by-employee/' . $this->employeeAllowedId);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'content' => [
                    'employee'   => ['id', 'first_name', 'last_name', 'emp_num', 'department_id', 'country_id'],
                    'date_range' => ['from', 'to'],
                    'daily',
                ],
            ]);
    }

    ###########################################################################
    ############################# Geo gate unit ###############################
    ###########################################################################

    public function testGeoGateRejectsForeignGeoForNonPrivilegedCaller()
    {
        $caller = User::find($this->callerId);
        $gate   = $this->app->make(AttendanceGeoGate::class);

        $this->assertTrue($gate->canAccessGeo($caller, $this->geoIdAllowed));
        $this->assertFalse($gate->canAccessGeo($caller, $this->geoIdOther));
    }

    ###########################################################################
    #################### Department master (EVOX-254) ########################
    ###########################################################################

    public function testDepartmentsMasterRejectsUnauthenticated()
    {
        $response = $this->getJson('/api/masters/departments');
        $this->assertContains($response->status(), [401, 403], 'Unauthenticated request must be rejected');
    }

    public function testDepartmentsMasterReturns200WithCorrectShape()
    {
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/masters/departments');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'message',
                'content',
            ]);

        $content = $response->json('content');
        $this->assertIsArray($content, 'content should be an array of department objects');

        # Find the seeded test department in the response.
        $found = collect($content)->firstWhere('id', $this->departmentId);
        $this->assertNotNull($found, 'Seeded test department must appear in the response');

        # Shape assertions on one item.
        $this->assertArrayHasKey('id',     $found);
        $this->assertArrayHasKey('name',   $found);
        $this->assertArrayHasKey('geo_id', $found);
        $this->assertIsInt($found['id']);
        $this->assertIsString($found['name']);
    }

    public function testDepartmentsMasterDerivedGeoIdMatchesUserCountry()
    {
        # The seeded test department has users with country_id = geoIdAllowed.
        # geo_id in the master response should resolve to geoIdAllowed.
        $response = $this->withHeaders($this->authHeaders($this->callerId))
            ->getJson('/api/masters/departments');

        $response->assertStatus(200);

        $found = collect($response->json('content'))->firstWhere('id', $this->departmentId);
        $this->assertNotNull($found);
        $this->assertEquals($this->geoIdAllowed, $found['geo_id'],
            'geo_id should match the country_id of the majority of active users in that department');
    }
}
