/**
 * EVOX — Jest: Redux Thunk Action Tests for freshServiceActions
 * Source: src/store/actions/freshservice/freshServiceActions.js  (was 0% coverage)
 *
 * COPY THIS FILE TO: client/src/__tests__/branchtests/store/actions/freshServiceActions.test.js
 * (relative imports below assume that location: src/__tests__/store/actions/ -> ../../../ reaches src/)
 *
 * NOTE: fetchWorkSpaces uses a MODULE-LEVEL `workspacesFetched` guard flag. To exercise
 * every branch (success, error, and the "already fetched -> skip" short-circuit) we
 * jest.resetModules() + re-require in beforeEach so the flag resets each test.
 *
 * API (src/services/API) + Formatter (src/services/Formatter) are mocked — NO real HTTP fires.
 *
 * Generated by AI (Claude Code) per the approved plan: scaffolding for developer review.
 */

const flushPromises = () => new Promise((resolve) => setImmediate(resolve));

describe('freshServiceActions (Redux thunks)', () => {
    let API;
    let Formatter;
    let fetchWorkSpaces;
    let dispatch;
    let getState;

    beforeEach(() => {
        jest.resetModules();

        // Re-declare mocks after resetModules so the fresh action module picks them up.
        jest.doMock('../../../../services/API', () => ({
            __esModule: true,
            default: { call: jest.fn() },
        }));
        jest.doMock('../../../../services/Formatter', () => ({
            __esModule: true,
            default: {
                alert_error: jest.fn((error) => ({ type: 'SHOW_ALERT', __mock: 'error', error })),
            },
        }));

        // Silence the console noise the action emits.
        jest.spyOn(console, 'log').mockImplementation(() => {});
        jest.spyOn(console, 'error').mockImplementation(() => {});

        API = require('../../../../services/API').default;
        Formatter = require('../../../../services/Formatter').default;
        fetchWorkSpaces = require('../../../../store/actions/freshservice/freshServiceActions').fetchWorkSpaces;

        dispatch = jest.fn();
        getState = jest.fn(() => ({}));
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    test('success: GETs /freshservice/workspaces/ and dispatches FETCH_WORKSPACES_SUCCESS', async () => {
        const result = {
            data: { content: ['WORKSPACES', 'CATEGORIES', 'SUB_CATEGORIES'] },
        };
        API.call.mockResolvedValueOnce(result);

        await fetchWorkSpaces()(dispatch, getState);
        await flushPromises();

        expect(API.call).toHaveBeenCalledWith({
            method: 'get',
            url: '/freshservice/workspaces/',
        });
        expect(dispatch).toHaveBeenCalledWith({
            type: 'FETCH_WORKSPACES_SUCCESS',
            workspaces: 'WORKSPACES',
            categories: 'CATEGORIES',
            sub_categories: 'SUB_CATEGORIES',
            isLoaded: true,
        });
        expect(Formatter.alert_error).not.toHaveBeenCalled();
    });

    test('error: dispatches alert_error when the API call rejects', async () => {
        const err = { status: 500, message: 'boom' };
        API.call.mockRejectedValueOnce(err);

        await fetchWorkSpaces()(dispatch, getState);
        await flushPromises();

        expect(Formatter.alert_error).toHaveBeenCalledWith(err);
        expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
    });

    test('guard: skips the API call when workspaces were already fetched', async () => {
        API.call.mockResolvedValue({ data: { content: ['a', 'b', 'c'] } });

        // First call flips the module-level flag to true.
        await fetchWorkSpaces()(dispatch, getState);
        await flushPromises();
        expect(API.call).toHaveBeenCalledTimes(1);

        dispatch.mockClear();
        API.call.mockClear();

        // Second call must short-circuit — no API call, no dispatch.
        await fetchWorkSpaces()(dispatch, getState);
        await flushPromises();

        expect(API.call).not.toHaveBeenCalled();
        expect(dispatch).not.toHaveBeenCalled();
    });
});
