/**
 * EVOX — Jest: Redux Thunk Action Tests for hr/hrAnnouncementsActions
 * Source: src/store/actions/hr/hrAnnouncementsActions.js  (hr/ was ~19% coverage)
 *
 * COPY THIS FILE TO: client/src/__tests__/branchtests/store/actions/hrActions.test.js
 * (relative imports below assume that location: src/__tests__/store/actions/ -> ../../../ reaches src/)
 *
 * hr/ contains a single action file (hrAnnouncementsActions.js); this suite covers every
 * exported creator in it on BOTH the .then (success) and .catch (error) branches.
 *
 * API (src/services/API) + Formatter (src/services/Formatter) are mocked — NO real HTTP fires.
 * global.links.dashboard is stubbed because the SET_REDIRECT dispatches read it.
 *
 * Generated by AI (Claude Code) per the approved plan: scaffolding for developer review.
 */

// ─── Service mocks (no real HTTP) ────────────────────────────────────────────
jest.mock('../../../../services/API', () => ({
    __esModule: true,
    default: { call: jest.fn() },
}));

jest.mock('../../../../services/Formatter', () => ({
    __esModule: true,
    default: {
        alert_success: jest.fn((result, timeOut) => ({
            type: 'SHOW_ALERT',
            __mock: 'success',
            result,
            timeOut,
        })),
        alert_error: jest.fn((error) => ({
            type: 'SHOW_ALERT',
            __mock: 'error',
            error,
        })),
    },
}));

import API from '../../../../services/API';
import Formatter from '../../../../services/Formatter';
import {
    fetchHrAnnouncements,
    fetchHrAnnouncement,
    addHrAnnouncements,
    updateHrAnnouncements,
    deleteHrAnnouncement,
    clearHrAnnouncementInstance,
} from '../../../../store/actions/hr/hrAnnouncementsActions';

const flushPromises = () => new Promise((resolve) => setImmediate(resolve));

// The redirect dispatches read global.links.dashboard.
global.links = { dashboard: '/app/Dashboard' };

describe('hrAnnouncementsActions (Redux thunks)', () => {
    let dispatch;
    let getState;
    const listResult = { data: { content: [{ id: 1, title: 'Notice' }] } };
    const okResult = { data: { message: 'Saved' } };
    const err = { status: 500, message: 'boom' };

    beforeEach(() => {
        jest.clearAllMocks();
        dispatch = jest.fn();
        getState = jest.fn(() => ({}));
    });

    // ─── fetchHrAnnouncements ────────────────────────────────────────────────
    describe('fetchHrAnnouncements', () => {
        test('success: GETs all + dispatches FETCH_HR_ANNOUNCEMENTS_LIST_SUCCESS', async () => {
            API.call.mockResolvedValueOnce(listResult);

            await fetchHrAnnouncements()(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'get',
                url: '/hr/announcements/all',
            });
            expect(dispatch).toHaveBeenCalledWith({
                type: 'FETCH_HR_ANNOUNCEMENTS_LIST_SUCCESS',
                list: listResult.data.content,
            });
        });

        test('error: dispatches alert_error', async () => {
            API.call.mockRejectedValueOnce(err);

            await fetchHrAnnouncements()(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });

    // ─── fetchHrAnnouncement (single) ────────────────────────────────────────
    describe('fetchHrAnnouncement', () => {
        test('success: GETs /hr/announcements/{id} + dispatches FETCH_HR_ANNOUNCEMENT_SUCCESS', async () => {
            API.call.mockResolvedValueOnce(listResult);

            await fetchHrAnnouncement(9)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'get',
                url: '/hr/announcements/9',
            });
            expect(dispatch).toHaveBeenCalledWith({
                type: 'FETCH_HR_ANNOUNCEMENT_SUCCESS',
                list: listResult.data.content,
            });
        });

        test('error: dispatches alert_error', async () => {
            API.call.mockRejectedValueOnce(err);

            await fetchHrAnnouncement(9)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });

    // ─── addHrAnnouncements ──────────────────────────────────────────────────
    describe('addHrAnnouncements', () => {
        const data = { title: 'New', body: 'Hello' };

        test('success: POSTs + dispatches alert_success then SET_REDIRECT', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await addHrAnnouncements(data)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'post',
                url: '/hr/announcements',
                data,
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_success.mock.results[0].value);
            expect(dispatch).toHaveBeenCalledWith({
                type: 'SET_REDIRECT',
                link: global.links.dashboard,
            });
        });

        test('error: dispatches alert_error and NOT SET_REDIRECT', async () => {
            API.call.mockRejectedValueOnce(err);

            await addHrAnnouncements(data)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
            expect(dispatch).not.toHaveBeenCalledWith(
                expect.objectContaining({ type: 'SET_REDIRECT' })
            );
        });
    });

    // ─── updateHrAnnouncements ───────────────────────────────────────────────
    describe('updateHrAnnouncements', () => {
        const data = { title: 'Edited' };

        test('success: POSTs /hr/announcements/{id} + alert_success + SET_REDIRECT', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await updateHrAnnouncements(3, data)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'post',
                url: '/hr/announcements/3',
                data,
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith({
                type: 'SET_REDIRECT',
                link: global.links.dashboard,
            });
        });

        test('error: dispatches alert_error', async () => {
            API.call.mockRejectedValueOnce(err);

            await updateHrAnnouncements(3, data)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });

    // ─── deleteHrAnnouncement ────────────────────────────────────────────────
    describe('deleteHrAnnouncement', () => {
        test('success: DELETEs /hr/announcements/{id} + alert_success + SET_REDIRECT', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await deleteHrAnnouncement(5)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'delete',
                url: '/hr/announcements/5',
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith({
                type: 'SET_REDIRECT',
                link: global.links.dashboard,
            });
        });

        test('error: dispatches alert_error', async () => {
            API.call.mockRejectedValueOnce(err);

            await deleteHrAnnouncement(5)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });

    // ─── clearHrAnnouncementInstance (synchronous, no API) ────────────────────
    describe('clearHrAnnouncementInstance', () => {
        test('dispatches CLEAR_HR_ANNOUNCEMENT_INSTANCE without calling the API', () => {
            clearHrAnnouncementInstance()(dispatch, getState);

            expect(dispatch).toHaveBeenCalledWith({
                type: 'CLEAR_HR_ANNOUNCEMENT_INSTANCE',
            });
            expect(API.call).not.toHaveBeenCalled();
        });
    });
});
