/**
 * EVOX — Jest: Redux Thunk Action Tests for teamActions
 * Source: src/store/actions/team/teamActions.js  (was 0% coverage)
 *
 * COPY THIS FILE TO: client/src/__tests__/branchtests/store/actions/teamActions.test.js
 * (relative imports below assume that location: src/__tests__/store/actions/ -> ../../../ reaches src/)
 *
 * Pattern (matches existing repo tests — jest.mock for services, no real HTTP):
 *   - API (src/services/API) and Formatter (src/services/Formatter) are jest.mock'd
 *     so NO real HTTP fires.
 *   - Each thunk is invoked with a mock dispatch + getState.
 *   - Every action creator is exercised on BOTH the .then (success) and .catch (error) branch.
 *
 * Generated by AI (Claude Code) per the approved plan: scaffolding for developer review.
 */

// ─── Service mocks (no real HTTP) ────────────────────────────────────────────
jest.mock('../../../../services/API', () => ({
    __esModule: true,
    default: { call: jest.fn() },
}));

jest.mock('../../../../services/Formatter', () => ({
    __esModule: true,
    default: {
        alert_success: jest.fn((result, timeOut) => ({
            type: 'SHOW_ALERT',
            __mock: 'success',
            result,
            timeOut,
        })),
        alert_error: jest.fn((error) => ({
            type: 'SHOW_ALERT',
            __mock: 'error',
            error,
        })),
    },
}));

import API from '../../../../services/API';
import Formatter from '../../../../services/Formatter';
import { createTeam, updateTeam, deleteTeam } from '../../../../store/actions/team/teamActions';

// Flush the microtask queue so .then()/.catch() chains (which the thunks do NOT return) settle.
const flushPromises = () => new Promise((resolve) => setImmediate(resolve));

describe('teamActions (Redux thunks)', () => {
    let dispatch;
    let getState;
    const okResult = { data: { message: 'OK' } };
    const err = { status: 500, message: 'boom' };

    beforeEach(() => {
        jest.clearAllMocks();
        dispatch = jest.fn();
        getState = jest.fn(() => ({}));
    });

    // ─── createTeam ──────────────────────────────────────────────────────────
    describe('createTeam', () => {
        const post_data = { name: 'Alpha Team' };

        test('success: POSTs to /team/ and dispatches alert_success', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await createTeam(post_data)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'post',
                url: '/team/',
                data: post_data,
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_success.mock.results[0].value);
        });

        test('error: dispatches alert_error on rejection', async () => {
            API.call.mockRejectedValueOnce(err);

            await createTeam(post_data)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
            expect(Formatter.alert_success).not.toHaveBeenCalled();
        });
    });

    // ─── updateTeam ──────────────────────────────────────────────────────────
    describe('updateTeam', () => {
        const team_id = 42;
        const post_data = { name: 'Renamed' };

        test('success: POSTs to /team/{id} and dispatches alert_success', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await updateTeam(team_id, post_data)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'post',
                url: '/team/42',
                data: post_data,
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_success.mock.results[0].value);
        });

        test('error: dispatches alert_error on rejection', async () => {
            API.call.mockRejectedValueOnce(err);

            await updateTeam(team_id, post_data)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });

    // ─── deleteTeam ──────────────────────────────────────────────────────────
    describe('deleteTeam', () => {
        const team_id = 7;

        test('success: DELETEs /team/{id} and dispatches alert_success', async () => {
            API.call.mockResolvedValueOnce(okResult);

            await deleteTeam(team_id)(dispatch, getState);
            await flushPromises();

            expect(API.call).toHaveBeenCalledWith({
                method: 'delete',
                url: '/team/7',
            });
            expect(Formatter.alert_success).toHaveBeenCalledWith(okResult, 3000);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_success.mock.results[0].value);
        });

        test('error: dispatches alert_error on rejection', async () => {
            API.call.mockRejectedValueOnce(err);

            await deleteTeam(team_id)(dispatch, getState);
            await flushPromises();

            expect(Formatter.alert_error).toHaveBeenCalledWith(err);
            expect(dispatch).toHaveBeenCalledWith(Formatter.alert_error.mock.results[0].value);
        });
    });
});
