name: Backend Tests

on:
  pull_request:
    branches:
      - master
      - develop
      - main

jobs:
  backend-tests:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Display workspace
        run: |
          pwd
          ls -la

      - name: Install Composer packages
        run: composer install --no-interaction --prefer-dist

      - name: Create testing environment
        working-directory: server
        run: |
          cat > .env.testing <<'EOF'
          DB_CONNECTION=mysql
          DB_HOST=10.10.4.24
          DB_PORT=3307
          DB_DATABASE=evox-app
          DB_USERNAME=laraveluser
          DB_PASSWORD=LaravelPass@20@#

          DB_EVOX_LOGS_CONNECTION=mysql
          DB_EVOX_LOGS_HOST=10.10.4.24
          DB_EVOX_LOGS_PORT=3307
          DB_EVOX_LOGS_DATABASE=evox-app
          DB_EVOX_LOGS_USERNAME=laraveluser
          DB_EVOX_LOGS_PASSWORD=LaravelPass@20@#
          EOF

      - name: Copy dompdf font cache
        run: |
          mkdir -p storage/fonts
          cp -r /var/www/html/evox-app-e2e/server/storage/fonts/* storage/fonts/

      - name: Run PHPUnit
        run: |
          mkdir -p reports

          vendor/bin/phpunit \
            --testsuite FeatureRoot \
            --coverage-html reports \
            --coverage-clover reports/coverage.xml

      - name: Check coverage
        run: php scripts/checkCoverage.php